# This is a basic workflow to help you get started with Actions

name: Winy Sloths Continuous Integration

on: 
  workflow_dispatch:
    branches: [ develop ]
    inputs:
        test_type:
          description: 'Test type (TU, TV or ALL)'
          required: true
          default: 'TU'
        symbol:
          description: 'Symbol (BTC, ETH or BNB)'
          required: true
          default: 'BTC'
        platform:
          description: 'Exchange platform (BINANCE, BYBIT or ALL)'
          required: true
          default: 'BINANCE'
        contract:
          description: 'Contract (SPOT, FUTURES or ALL)'
          required: true
          default: 'SPOT'
jobs:
  ARTEFACTS:
    name: Publish artefacts 📣
    #needs: [TV_BINANCE, UML, QUALITY, DOCUMENTATION]
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
  
  # Add traduction sphinx
  # Traduction failed